
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 1800

  #  _____               _    _____  _____   _   _             _            
  # /  __ \             | |  |  _  |/  ___| | \ | |           | |           
  # | /  \/  ___  _ __  | |_ | | | |\ `--.  |  \| |  ___    __| |  ___  ___ 
  # | |     / _ \| '_ \ | __|| | | | `--. \ | . ` | / _ \  / _` | / _ \/ __|
  # | \__/\|  __/| | | || |_ \ \_/ //\__/ / | |\  || (_) || (_| ||  __/\__ \
  #  \____/ \___||_| |_| \__| \___/ \____/  \_| \_/ \___/  \__,_| \___||___/

# node01
config.vm.define "ansible-node01" do |cfg|
  cfg.vm.box = "centos/7"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "Ansible-Node01"
    vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
    #vb.cpus = 2 cpu 2개
  end
  cfg.vm.host_name = "ansible-node01"
  cfg.vm.network "private_network", ip: "192.168.56.101"
  cfg.vm.network "forwarded_port", guest:22, host: 60101, auto_correct: true, id: "ssh"
  cfg.vm.network "forwarded_port", guest:80, host: 60081, auto_correct: true
  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  cfg.vm.provision "shell", path:"bash_ssh_conf_4_CentOS.sh"
end


# node02
config.vm.define "ansible-node02" do |cfg|
  cfg.vm.box = "centos/7"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "Ansible-Node02"
    vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
  end
  cfg.vm.host_name = "ansible-node02"
  cfg.vm.network "private_network", ip: "192.168.56.102"
  cfg.vm.network "forwarded_port", guest:22, host: 60102, auto_correct: true, id: "ssh"
  cfg.vm.network "forwarded_port", guest:80, host: 60082, auto_correct: true
  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  cfg.vm.provision "shell", path:"bash_ssh_conf_4_CentOS.sh"
end

# node03
config.vm.define "ansible-node03" do |cfg|
  cfg.vm.box = "centos/7"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "Ansible-Node03"
    vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
  end
  cfg.vm.host_name = "ansible-node03"
  cfg.vm.network "private_network", ip: "192.168.56.103"
  cfg.vm.network "forwarded_port", guest:22, host: 60103, auto_correct: true, id: "ssh"
  cfg.vm.network "forwarded_port", guest:80, host: 60083, auto_correct: true
  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  cfg.vm.provision "shell", path:"bash_ssh_conf_4_CentOS.sh"
end



#  _   _  _                    _            _   _             _            
# | | | || |                  | |          | \ | |           | |           
# | | | || |__   _   _  _ __  | |_  _   _  |  \| |  ___    __| |  ___  ___ 
# | | | || '_ \ | | | || '_ \ | __|| | | | | . ` | / _ \  / _` | / _ \/ __|
# | |_| || |_) || |_| || | | || |_ | |_| | | |\  || (_) || (_| ||  __/\__ \
#  \___/ |_.__/  \__,_||_| |_| \__| \__,_| \_| \_/ \___/  \__,_| \___||___/
                                                                         
# node04
config.vm.define "ansible-node04" do |cfg|
  cfg.vm.box = "ubuntu/trusty64"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "Ansible-Node04"
    vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
  end
  cfg.vm.host_name = "ansible-node04"
  cfg.vm.network "private_network", ip: "192.168.56.201"
  cfg.vm.network "forwarded_port", guest:22, host: 60201, auto_correct: true, id: "ssh"
  cfg.vm.network "forwarded_port", guest:80, host: 60084, auto_correct: true
  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
end

# node05
config.vm.define "ansible-node05" do |cfg|
  cfg.vm.box = "ubuntu/trusty64"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "Ansible-Node05"
    vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
  end
  cfg.vm.host_name = "ansible-node05"
  cfg.vm.network "private_network", ip: "192.168.56.202"
  cfg.vm.network "forwarded_port", guest:22, host: 60202, auto_correct: true, id: "ssh"
  cfg.vm.network "forwarded_port", guest:80, host: 60085, auto_correct: true
  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
end

# node06
config.vm.define "ansible-node06" do |cfg|
  cfg.vm.box = "ubuntu/trusty64"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "Ansible-Node06"
    vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
  end
  cfg.vm.host_name = "ansible-node06"
  cfg.vm.network "private_network", ip: "192.168.56.203"
  cfg.vm.network "forwarded_port", guest:22, host: 60203, auto_correct: true, id: "ssh"
  cfg.vm.network "forwarded_port", guest:80, host: 60086, auto_correct: true
  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
end

end

#   ___               _  _      _         _____                                
#  / _ \             (_)| |    | |       /  ___|                               
# / /_\ \ _ __   ___  _ | |__  | |  ___  \ `--.   ___  _ __ __   __  ___  _ __ 
# |  _  || '_ \ / __|| || '_ \ | | / _ \  `--. \ / _ \| '__|\ \ / / / _ \| '__|
# | | | || | | |\__ \| || |_) || ||  __/ /\__/ /|  __/| |    \ V / |  __/| |   
# \_| |_/|_| |_||___/|_||_.__/ |_| \___| \____/  \___||_|     \_/   \___||_|   

Vagrant.configure("2") do |config|
  config.vm.define "ansible-server" do |cfg|
  cfg.vm.box = "centos/7"
  cfg.vm.provider "virtualbox" do |vb|
    vb.name = "Ansible-Server"
    vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
  end
  cfg.vm.host_name = "ansible-server"
  cfg.vm.network "private_network", ip: "192.168.56.10"
  cfg.vm.network "forwarded_port", guest:22, host: 60010, auto_correct: true, id: "ssh"
  cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  cfg.vm.provision "shell", inline: "yum install epel-release -y" # 새로운 레포지토리 주소 받아오기
  cfg.vm.provision "shell", inline: "yum install ansible -y"
  cfg.vm.provision "file", source: "ansible_env_ready.yml",
    destination: "ansible_env_ready.yml"
  cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  cfg.vm.provision "file", source: "auto_pass.yml", destination: "auto_pass.yml"
  cfg.vm.provision "shell", inline: "ansible-playbook auto_pass.yml", privileged: false
  end
end
 
